"""Import a per-bank flow seed onto any machine's arm.

Reads a seed file produced by db/export_bank_seed.py, substitutes the
{ARM_NAME} placeholder with the caller-supplied arm name, then pipes the
SQL into the Docker MySQL container.

Usage:
    py db/import_bank_seed.py <seed_file> <ARM_NAME>
    py db/import_bank_seed.py db/seed_bank_ABA.sql ARM-05
    py db/import_bank_seed.py db/seed_bank_CIMB.sql ARM-08

Prerequisites:
  - Docker Desktop running with container wa-unified-mysql up
  - The target arm row already exists in the arms table (Settings -> Arms in Builder)
  - WA service should be stopped or paused during import to avoid mid-write
    race conditions (though the import is idempotent and safe to re-run)

After import:
  - Flows are visible in Builder immediately
  - All ui_element_key / swipe_key / keymap_type references point to names
    that need to be wired up in Settings -> Coordinates for this machine
  - Run calibration (INSTALL.md Step 9) and capture references per arm
"""
import os
import subprocess
import sys

CONTAINER = "wa-unified-mysql"
DB_USER = "root"
DB_PASS = "wa_unified_2026"
DB_NAME = "wa_db"


def main():
    if len(sys.argv) < 3:
        print("Usage: py db/import_bank_seed.py <seed_file> <ARM_NAME>")
        print("  e.g: py db/import_bank_seed.py db/seed_bank_ABA.sql ARM-05")
        sys.exit(1)

    seed_file = sys.argv[1]
    arm_name = sys.argv[2]

    if not os.path.exists(seed_file):
        print("ERROR: seed file not found: %s" % seed_file)
        sys.exit(1)

    with open(seed_file, "r", encoding="utf-8") as f:
        sql = f.read()

    if "{ARM_NAME}" not in sql:
        print("ERROR: seed file does not contain the {ARM_NAME} placeholder.")
        print("  Was this file generated by db/export_bank_seed.py?")
        sys.exit(1)

    # Substitute placeholder with the target arm name.
    sql = sql.replace("{ARM_NAME}", arm_name)

    # Pre-check: confirm arm exists in DB before doing anything.
    check = subprocess.run(
        ["docker", "exec", CONTAINER,
         "mysql", "-u", DB_USER, "-p" + DB_PASS, "-N", "-B",
         "-e", "SELECT id FROM %s.arms WHERE name='%s';" % (DB_NAME, arm_name)],
        capture_output=True, timeout=15,
    )
    arm_id_raw = check.stdout.decode("utf-8", errors="replace").strip()
    if not arm_id_raw:
        print("FAILED: arm '%s' does not exist in the database." % arm_name)
        print()
        print("  Fix: open Builder -> Settings -> Arms and add an arm named '%s'." % arm_name)
        print("  Then re-run this command.")
        sys.exit(1)

    print("Importing %s for arm '%s' (arm_id=%s) ..." % (
        os.path.basename(seed_file), arm_name, arm_id_raw))

    proc = subprocess.run(
        ["docker", "exec", "-i", CONTAINER,
         "mysql", "-u", DB_USER, "-p" + DB_PASS, DB_NAME],
        input=sql.encode("utf-8"),
        capture_output=True,
        timeout=60,
    )

    stderr = proc.stderr.decode("utf-8", errors="replace")
    stdout = proc.stdout.decode("utf-8", errors="replace")

    # mysql prints warnings via stderr; only treat non-warning lines as errors.
    real_errors = [l for l in stderr.splitlines() if l and "Warning" not in l]

    if proc.returncode != 0 or real_errors:
        print("FAILED (exit code %d)" % proc.returncode)
        for l in real_errors:
            print("  STDERR: %s" % l)
        if stdout.strip():
            print("  STDOUT: %s" % stdout.strip())
        sys.exit(1)

    # Print MySQL output (SELECT result from the final confirmation query).
    if stdout.strip():
        print(stdout.strip())

    print("OK - import complete.")
    print()
    print("Next steps for arm '%s':" % arm_name)
    print("  1. Open Builder -> Settings -> Coordinates")
    print("     Record ui_elements, swipe_actions, keymaps for each bank step")
    print("  2. Run calibration (Builder -> Calibrate) for each station")
    print("  3. Capture CHECK_SCREEN references (Builder -> Capture Now on each step)")


if __name__ == "__main__":
    main()
